### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by HMAZonderland** [websafe/lib-websafe-blueimp-jquery-file-upload-handler#1]
I see there have been several updates to the upload handler class. The current version is 8.4.1.

https://github.com/blueimp/jQuery-File-Upload/commit/e41d9e0b7d74fb419b2788e6c09601f2a66e65d6

Please update your library.

**Comment by websafe** [comment]
@HMAZonderland thanks for noticing, I forgot about tagging releases :-) Build script was updated and the library is now **v9.11.2**.

https://packagist.org/packages/websafe/lib-websafe-blueimp-jquery-file-upload-handler

**Comment by HMAZonderland** [comment]
Thanks. I'll notify you when needed!
